AftermathFinance/aftermath-sdk-rust

.github/workflows/cd.yml
- 4e4544b **ci: limit concurrent CD workflows for the same commit**
Since `cargo workspaces` will publish all unpublished crates, we don't
need to run the CD workflow twice for the same commit SHA, regardless if
more than one tag was created for it
- 5504ac4 **ci: add pull-request workflow**
Try to enforce linear history + signed commits for the `main` branch by
leveraging a GitHub action to perform fast-forward merges.
=> Workflow improvements

.github/workflows/fast-forward.yml
It seems that fast-forwards by the workflow with the standard
GITHUB_TOKEN don't trigger actions. Try using the same token as
release-please in order to trigger them
=> ci: use personal access token for fast-forward workflow

crates/af-ptbuilder/Cargo.toml, crates/af-ptbuilder/examples/builder_serde.rs, crates/af-ptbuilder/proptest-regressions/tests.txt, crates/af-ptbuilder/src/lib.rs, crates/af-ptbuilder/src/tests.rs
Adds
- conversions from/to `ProgrammableTransaction` to
`ProgrammableTransactionBuilder`
- `#[derive(Clone, Debug)]` for `ProgrammableTransactionBuilder`
To ensure this is working, a proptest and an example were added.
=> feat(af-ptbuilder): conversions from/to a Sui PTB

crates/af-sui-types/src/lib.rs, crates/af-sui-types/src/sui/transaction/mod.rs
This was previously hidden, so dependents couldn't wrap it or match
against its variants
=> feat(af-sui-types): export `TransactionFromBase64Error`

crates/af-sui-types/src/sui/transaction/data.rs
Use an opaque type so we can change how we decode base64 in the future;
for instance, using the `base64ct` crate
=> feat(af-sui-types): use string for `TransactionFromBase64Error::Base64`

crates/pyth-hermes-client/Cargo.toml, crates/pyth-hermes-client/examples/price_update_stream.rs, crates/pyth-hermes-client/src/lib.rs, crates/pyth-hermes-client/src/stream.rs
- 1288fdc **feat!: make streams optional and allow tls backend choices**
By default, `pyth-hermes-client` will use the `rustls-tls` feature of
`reqwest`, since most likely this will be used to make request to
external Pyth Hermes services via HTTPS
On the other hand, `stream` is an optional feature that guards the SSE
price stream implementation. Enable that feature if you want price
subscriptions.
- 5d7a984 **chore: default value for pyth-price-update-stream example**
---
1. Tested it with `cargo hack -p pyth-hermes-client --keep-going --feature-powerset clippy --all-targets`
1. `cd crates/pyth-hermes-client`
1. `cargo run --example pyth-price-feeds`
Without any TLS backend, which `reqwest = { default-features = false, ... }` would imply, we would not be able to connect to either …
=> pyth hermes features

crates/sui-gql-client/Cargo.toml, crates/sui-gql-client/README.md, crates/sui-gql-client/src/extract.rs, crates/sui-gql-client/src/queries/mod.rs
- 810aa83 **fix: required features**
Some tests would fail to compile under some feature combinations because
the dependencies weren't properly listed in `[dev-dependencies]`
- 34dcfc3 **feat: disable `reqwest` default features**
For TLS backends, enable the `reqwest` feature for the backend you want
to use.
---
You need to import the TLS backend feature yourself in order to use HTTPS. Since this crate only provides a client implementation using `reqwest`, that means enabling one of its TLS features, e.g.,
- `reqwest = { features = ["native-tls"], ... }`
- `reqwest = { features = ["rustls-tls"], ... }`
Otherwise, you'll get an error like
```
$ cargo run --example gql-latest-checkpoint 
Error: 
0: Client error: Inner(ReqwestError(reqwest::Error { kind: Request, url: …
```
=> Disable `reqwest` default features for GraphQL client

crates/af-sui-types/src/sui/transaction/data.rs
This method looks more useful as associated function
=> fix: remove redundant `&safe` in `TransactionData` decode function

crates/af-iperps/Cargo.toml, crates/af-oracle/Cargo.toml, crates/af-pyth-wrapper/Cargo.toml
These dependents use the crate's types in their public API, so they must
go through a major version bump after the crate goes through one.
=> chore: bump `af-utilities` dependents

crates/sui-jsonrpc/src/msgs/sui_transaction.rs
The first commit is a consequence of an addition to `JSON-RPC` in `testnet-v1.45.0`. Unfortunately, it is a breaking change **on the Rust side**, but only there, since the struct wasn't marked as `non_exhaustive`.
The second commit addresses a bug that was already there.
- **feat(sui-jsonrpc)!: add `DryRunTransactionBlockResponse::execution_error_source`**
- **fix(sui-jsonrpc): recreate `UserSignature` serialization used in the RPC**
=> testnet v1.45.0

crates/pyth-sui-sdk/Cargo.toml
This crate uses types from `sui-jsonrpc` in its public API when feature
`json-rpc` is enabled
=> feat!: bump minor version due to public dependency on `sui-jsonrpc`

crates/pyth-hermes-client/src/stream.rs
This was preventing users from acquiring mutable references to types
containing the client as the borrow checker would believe the latter was
being immutably borrowed while the stream was alive
=> fix!: signal that stream doesn't use the client's lifetime

crates/af-keys/Cargo.toml, crates/af-keys/src/crypto.rs
- 1ff5f2b **feat(af-keys)!: upgrade `fastcrypto` dep**
`fastcrypto` has a breaking change that was not conveyed through SemVer.
We properly communicate that wherever we were forced to update the
errors (implementing their trait interfaces)
=> feat(af-keys)!: upgrade `fastcrypto` dep

crates/af-iperps/src/event_instance.rs, crates/af-iperps/src/snapshots/af_iperps__tests__public_api.snap
This isn't a breaking change because `EventInstance` is a non-exhaustive
enum.
=> fix(af-iperps): add `EventInstance::FilledMakerOrders`

crates/af-sui-types/src/sui/object.rs
This method will not be documented or suggested by LSPs to avoid
misinterpretation. However, it is necessary to be public so that users
can reconstruct the Move struct's BCS
=> feat(af-sui-types): expose hidden `MoveObject::has_public_transfer`

crates/af-keys/src/multisig.rs, crates/af-sui-types/src/sui/transaction/data.rs, crates/sui-gql-client/examples/object_args.rs, crates/sui-gql-client/src/queries/mod.rs, crates/sui-gql-client/src/queries/object_arg.rs, crates/sui-gql-client/src/queries/object_args.rs, crates/sui-jsonrpc/src/client.rs, crates/sui-jsonrpc/src/msgs/sui_transaction.rs
Also optimizes `object_args!` when there's only one to fetch
=> feat(sui-gql-client): `GraphQlClientExt::object_arg`

crates/af-sui-types/Cargo.toml, crates/af-sui-types/src/sui/transaction/data.rs
- **chore(af-sui-types): remove erroneus deprecation**
- **test(af-sui-types): ensure TransactionData roundtrip through base64 is valid**
=> af sui types patch

crates/af-iperps/Cargo.toml, crates/af-iperps/src/errors.rs, crates/af-iperps/src/snapshots/af_iperps__tests__public_api.snap, crates/sui-jsonrpc/Cargo.toml, crates/sui-jsonrpc/src/client.rs, crates/sui-jsonrpc/src/error.rs, crates/sui-jsonrpc/src/msgs/sui_transaction.rs
- f97d1fe **feat(sui-jsonrpc): better coin queries**
- 03d139f **feat(sui-jsonrpc): `SuiClient::submit_transaction`**
- 468b6f3 **feat(sui-jsonrpc)!: `SuiTransactionBlockResponse::sui_effects`**
Helper to get the network's effects format from the JSON-RPC response
- ec45741 **feat(sui-jsonrpc): `SuiClient::dry_run_transaction`**
- 3a320bd **refactor(af-iperps): Move abort code consts conversion to Rust**
- d43e801 **feat(af-iperps): `MoveAbort` enum with all error codes and documentation**
This implements:
- conversions from numerical codes (what we get in `TransactionEffects`)
- the error documentation, derived from the Move source, using `strum::EnumMessage`
- the error variant to string using `strum::IntoStaticStr`
=> `SuiClient` and `af_iperps::errors` improvements

crates/pyth-sui-sdk/Cargo.toml
- 8ce4d23 **fix: bump SemVer-breaking version for `pyth-sui-sdk`**
The crate depends publicly on `sui-jsonrpc` due to
`pyth_sui_sdk::read::get_price_info_object_id_from_pyth_state` which
uses `WriteApiClient`.
Since `sui-jsonrpc` was erroneously updated (SemVer-breaking), then this
needs to be as well.
=> fix: bump SemVer-breaking version for `pyth-sui-sdk`

crates/af-sui-pkg-sdk/examples/display.rs, crates/af-sui-pkg-sdk/src/lib.rs, crates/af-sui-pkg-sdk/tests/option_field.rs, crates/af-sui-pkg-sdk/tests/tests.rs
Self-explanatory. This gets around the issue that `Option<T>` doesn't
implement `Display` by using the `#[tabled(format(...))]` attribute.
In a future breaking change of `af-sui-pkg-sdk`, this could be used for
`vector<T>` fields to avoid the `MoveVec` type which is annoying to use
=> feat(af-sui-pkg-sdk): support `Option<T>` type fields
